export interface SiteConfigure {
    businessUnitCode: string,
    businessUnit: string,
    default: boolean,
    businessNumber: string,
    companyNumber: string,
    address: string,
    businessUnitColor: string,
    contactEmail: string,
    contactNumber: string,
    contactFax: string,
    contactName: string,
    logoURL: string,
    smallLogoURL: string,
    websiteURL: string,
    imageFolderURL: string,
    defaultTheme: string,
    defaultLanguage: string,
    defaultCurrencyCode: string,
    defaultSASSURL: string
}