/**
 * Selcomm API
 * Selcomm APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gielisg@selectsoftware.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A general purpose key - value pair list plus a catgeorisation field
 */
export interface CategorisedKeyValuePairListItem { 
    /**
     * The key of the item
     */
    key?: string;
    /**
     * Value of the item
     */
    value?: string;
    /**
     * Category of the item
     */
    category?: string;
}
