export interface CollectionRunAuthoriseDetailListItem {
    CollectionAttempt: number,
    DebtorCode: string,
    ServiceId: number,
    BillId: number,
    InvoiceNumber: string,
    PayMethodId: number,
    TransactionStatus: string,
    AccountBalance: number,
    FutureCredits: number,
    FutureDebits: number,
    SurchargeAmount: number,
    CollectionAmount: number,
    ExchangeAmount: number,
    ExchangeRateReference: string,
    CreatedBy: string,
    CreatedDatetime: string,
    UpdatedBy: string,
    LastUpdatedDatetime: string,
}
