export interface ChargeItem {
    Code: string,
    Description: string,
    Freq: string,
    ChargeStart: string,
    ChargeEnd: string,
    ChargeTo: string,
    AmountDefault: number,
    CostTax: number,
    Source: string,
    Package: string,
    PackageOption: string,
    ProRata: string,
    ChargeType: string,
    ProductCode: string,
    ChargeRef: string,
    OverrideId: string,
    NetworkDetailRef: string,
    Discount: string,
    FileType: string,
    CreatedTime: string,
    CreatedBy: string,
    LastUpdated: string,
    UpdatedBy: string
}
