export interface ServiceItem {
    Id: string,
    IsChildService: boolean,
    IsService: boolean,
    Label: string,
    ParentId: string,
    ServiceCount: string,
    ServiceInstanceMenuId: number,
    ServiceType: string,
    ServiceTypeCount: number,
    ServiceTypeId: string,
    ServiceTypeImage: string,
    ServiceTypeMenuId: number,
    Status: string,
    StatusId: string,
    SystemStatus: string,
    SystemStatusId: string,
    ServiceNumber: string,
}
